### ISSUE TITLE
Домашка №3 (ООП)

### ISSUE THREAD

**Issue by kottans-net** [Rudeka/KottansHomeWork#4]
Предлагаем вам выполнить домашку по ООП https://github.com/Zaknafeyn/OOP.Task

**Comment by Rudeka** [comment]
Task is closed, solution added to the repository https://goo.gl/sNq6KX

**Comment by zaknafeyn** [comment]
Проверено.
Замечания:
- хорошо, что делаешь проверку на 0 когда делаешь вычисления с Multiplier, но плохо, что эту проверку надо делать каждый раз - это дублирование кода. Намного лучше было бы делать такую проверку в сеттере свойства Multiplier и в случае если присваивается значение 0, присваивать значение 1. Например так:
  private byte _multiplier = 1; 
  public byte Multiplier { get{return (byte)_multiplier;} set{_multiplier = value == 0 ? 1 : value;} }
- метод Move один для всех, его лучше вынести в самый базовый класс
- реализация метод Area для обычного треугольника подходит для всех треугольников, поэтому его можно переиспользовать. Но, если ты хочешь вычислять площадь оптимальным способом для каждого типа треугольника, то лучше тогда делать реализацию метода Area для каждого треугольника отдельно. У тебя же площадь прямоугольного треугольника вычисляется по формуле Герона (которая не очень оптимальная). Это не ошибка, а информация к размышлению
